# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_combustible', models.DecimalField(decimal_places=0, max_digits=6)),
                ('energia_generada', models.DecimalField(decimal_places=0, max_digits=6)),
                ('consumo_aceite_motor', models.DecimalField(decimal_places=0, max_digits=6)),
                ('consumo_agua', models.DecimalField(decimal_places=0, max_digits=6)),
                ('fecha', models.DateField()),
                ('emplazamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_control_produccion_indicadores.Emplazamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Tenologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='emplazamiento',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_control_produccion_indicadores.Tenologia'),
        ),
    ]
