# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_control_produccion_indicadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenologia',
            new_name='Tecnologia',
        ),
    ]
